apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t7np7gtbk-go 
  janus-idp.io/tekton: t7np7gtbk-go
  backstage.io/kubernetes-id: t7np7gtbk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t7np7gtbk-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml